- name: create dashboard file
  ansible.builtin.template:
    src: dashboard.json
    dest: /tmp/dashboard.json

- name: ADD Grafana dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://172.31.38.199:3000
    #grafana_api_key: "{{ lookup('amazon.aws.aws_ssm', 'grafana.api_key', region='us-east-1' ) }}"
    grafana_api_key: "glsa_DGjmoL8Bb6wVbUTnZk3mzTXS0bmZrePh_137c251f"
    state: present
    commit_message: Updated by ansible
    overwrite: yes
    path: /tmp/dashboard.json

