tasks:
  - name: Disable nodeJS deafult version
    ansible.builtin.shell: dnf module disable nodejs -y
  - name: Enable nodeJS 18 version
    ansible.builtin.shell: dnf module enable nodejs:18 -y
  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: copy backend service
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service
  - name: Add application user
    ansible.builtin.user:
      name: expense
  - name: Delete old content
    ansible.builtin.file:
      path: /app
      state: absent
  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: dowanload and exract the file
    ansible.builtin.unarchive:
      src: https://expense-artifacts.s3.amazonaws.com/backend.zip
      dest: /app
      remote_src: yes
  - name: dowanload nodejs dependencies
    ansible.builtin.shell: npm install
    args:
      chdir: /app
  - name: install mysql
    ansible.builtin.dnf:
      name: mysql
      state: present
  - name: load schema
    ansible.builtin.shell: mysql -h mysql-dev.nadevops.online -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql
  - name: backend service start
    ansible.builtin.service:
      name: backend
      state: restarted
      enabled: yes

