  - name: Installing Nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: copy expense config file
    ansible.builtin.template:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: import the role
    ansible.builtin.import_role:
      name: common
      tasks_from: app-prereq
    vars :
      app_dir: /usr/share/nginx/html
      variable: frontend

  - name: start nginx services
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes

  - name: import the elk filebeat repo file
    ansible.builtin.import_role:
      name: elk
      tasks_from: filebeat

  - name: import the node exporter file
    ansible.builtin.import_role:
      name: prometheus
      tasks_from: node-exporter.yml

  - name: import the grafana
    ansible.builtin.import_role:
      name: grafana

  - name: copy or generate the alert YAML file
    ansible.builtin.template:
      src: alert-rules.yml
      dest: /tmp/{{component}}-{{env}}.yml

  - name: Upload the file to s3 bucket
    community.aws.s3_sync:
      bucket: nabi-prometheus-alert-rules
      file_root: /tmp/{{component}}-{{env}}.yml

