tasks:
  - name: Installing Nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: copy expense config file
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf
  - name: clean the old nginx directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  - name: create new directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: dowanload and exract the file
    ansible.builtin.unarchive:
      src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  - name: start nginx services
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes



