- name: copy the elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install the filebeat packages
  ansible.builtin.dnf:
    name: filebeat
    state: present

- name: copy filebeat configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: restart the filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes
