- name: copy the prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: copy alert rules
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /opt/prometheus/alert-rules.yml

- name: restart the prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes

- name: copy the alert manager config
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart the alertmanager
  ansible.builtin.systemd:
    name: alertmanager.yml
    state: restarted
    enabled: yes





