route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'SNS'
receivers:
  - name: SNS
    sns_configs:
    - sigv4:
        region: us-est-1
      topic_arn: arn:aws:sns:us-east-1:146677740583:email1
      subject: prometheus alert
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
